### ISSUE TITLE
WOW !!!!

### ISSUE THREAD

**Issue by AlexanderMaydorf** [billkenney/revert_qidi_software#1]
Why you are the only person - just fixing the problem?

Got my printer 2 days ago... 
USB drive was damaged - downloaded latest software.... printed something...
Next day after restart - ERROR messages...

GOOGLE: Lot of stupid suggestions... flashing firmware, make new configurations / installs .... 

And you ? ... just an easy and simple solution which worked after the first try !!!!

Thank you so much!

Alexander

**Comment by billkenney** [comment]
@AlexanderMaydorf 

You've got me there. I opened an issue on Qidi's GitHub asking them to add this fix to their wiki months ago. They said they would but it's still not on there...

Glad it helped you get back up and running!

You should join these Facebook groups. If you have any questions about the printer (including this issue) you usually get at least a handful of responses quickly. The 3d printer group is better than the official group imo

https://www.facebook.com/share/1x1cezvuMR8hDZ94/?mibextid=K35XfP

https://www.facebook.com/share/LMtBfJzqpBW8i2xw/?mibextid=K35XfP
