### ISSUE TITLE
Qidi Plus 4 the system starts abnormally

### ISSUE THREAD

**Issue by DeeMon4eg** [billkenney/revert_qidi_software#2]
You have a great article on restoring firmware for qidi max3/plus3/smart3.
Can you help with a similar problem for qidi plus4?
I'm bad at Linux commands.

**Comment by billkenney** [comment]
I think the Plus4 runs on the same OS and has updated klipper/moonraker/fluidd, but the firmware is obviously different. Best advice I could give is to reinstall the firmware.

**Comment by DeeMon4eg** [comment]
That's exactly what I wanted to do.
But as I understood, there are different commands for all printers, according to your instructions.
Which one will be for plus4? As I wrote, I'm weak in Linux.

**Comment by billkenney** [comment]
You don't need to use Linux. Just put the firmware files on a flash drive. 
https://wiki.qidi3d.com/en/PLUS4/Manual/firmware-update

**Comment by DeeMon4eg** [comment]
Unfortunately, this did not help. "the system starts abnormally" still appears on the screen.
At the same time, it has stopped connecting via ssh.

**Comment by billkenney** [comment]
I don't have the plus 4, so I'm not able to help. You need to contact Qidi for support.
