### ISSUE TITLE
after update

### ISSUE THREAD

**Issue by Ferropluss** [billkenney/revert_qidi_software#3]
![IMG_20241224_132307_333](https://github.com/user-attachments/assets/94777e43-f25a-491e-815a-8c5a338581b3)
![IMG_20241224_132256_518](https://github.com/user-attachments/assets/6da5a9d8-714f-4744-82a2-dc3950713a5b)
not a single sensor is working

**Comment by billkenney** [comment]
This wouldn't have anything to do with rolling back to working versions of klipper or moonraker. I'll address this in the recovery repository.
